version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evision
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/evision
      CREATE_TABLES_ON_START: "True"
    ports:
      - "8000:8000"
    volumes:
      - ./ml/models:/app/ml/models

volumes:
  pgdata:
