"""
Template for Alembic autogenerated revision scripts.
"""
<%!
from alembic import op
import sqlalchemy as sa
%>
"""Empty upgrade and downgrade - fill in with autogenerate or manual operations."""
def upgrade():
    pass

def downgrade():
    pass
