"""core schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_hours',
    sa.Column('hour', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('band', sa.String(length=20), nullable=False),
    sa.Column('rate_inr_per_kwh', sa.Float(), nullable=False),
    sa.CheckConstraint('hour BETWEEN 0 AND 23', name='valid_hour'),
    sa.PrimaryKeyConstraint('hour')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('battery_capacity_kwh', sa.Float(), nullable=False),
    sa.Column('rated_range_km', sa.Float(), nullable=False),
    sa.Column('registered_on', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('battery_capacity_kwh > 0', name='battery_capacity_positive'),
    sa.CheckConstraint('rated_range_km > 0', name='rated_range_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_vehicles_owner_id'), 'vehicles', ['owner_id'], unique=False)
    op.create_table('charging_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('charger_type', sa.Enum('home_ac', 'public_ac', 'dc_fast', name='charger_type'), nullable=False),
    sa.Column('start_soc_pct', sa.Float(), nullable=False),
    sa.Column('end_soc_pct', sa.Float(), nullable=False),
    sa.Column('energy_delivered_kwh', sa.Float(), nullable=False),
    sa.Column('max_power_kw', sa.Float(), nullable=True),
    sa.Column('cost_inr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_soc_pct >= start_soc_pct', name='soc_does_not_drop'),
    sa.CheckConstraint('ended_at > started_at', name='ends_after_start'),
    sa.CheckConstraint('energy_delivered_kwh >= 0', name='energy_non_negative'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'started_at', name='uq_charging_vehicle_start')
    )
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_type', sa.Enum('battery_health', 'range', name='prediction_type'), nullable=False),
    sa.Column('reference_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_lookup', 'predictions', ['vehicle_id', 'prediction_type', 'reference_time'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('odometer_km', sa.Float(), nullable=False),
    sa.Column('speed_kph', sa.Float(), nullable=False),
    sa.Column('soc_pct', sa.Float(), nullable=False),
    sa.Column('soh_pct', sa.Float(), nullable=True),
    sa.Column('battery_voltage_v', sa.Float(), nullable=False),
    sa.Column('battery_current_a', sa.Float(), nullable=False),
    sa.Column('battery_temp_c', sa.Float(), nullable=False),
    sa.Column('motor_temp_c', sa.Float(), nullable=True),
    sa.Column('ambient_temp_c', sa.Float(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'recorded_at', name='uq_telemetry_vehicle_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    op.drop_index('ix_predictions_lookup', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('charging_sessions')
    op.drop_index(op.f('ix_vehicles_owner_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('tariff_hours')
    # ### end Alembic commands ###
    sa.Enum(name='prediction_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='charger_type').drop(op.get_bind(), checkfirst=True)
